# Generated by Django 4.1 on 2022-08-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0009_alter_boardinghouse_options_boardinghouse_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='phone',
            field=models.IntegerField(verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(verbose_name='Contact Number'),
        ),
    ]
