# Generated by Django 4.1 on 2022-08-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0010_alter_boardinghouse_phone_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
