# Generated by Django 4.1 on 2022-08-14 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0024_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardinghouse',
            old_name='picture',
            new_name='imagess',
        ),
    ]
