# Generated by Django 4.1 on 2022-08-14 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0025_rename_picture_boardinghouse_imagess'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boardinghouse',
            old_name='imagess',
            new_name='picture',
        ),
    ]
