# Generated by Django 4.1 on 2022-08-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0028_alter_boardinghouse_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='phone',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(max_length=200, verbose_name='Contact Number'),
        ),
    ]
