# Generated by Django 4.1 on 2022-08-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_App', '0029_alter_boardinghouse_phone_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinghouse',
            name='phone',
            field=models.IntegerField(verbose_name='Contact Number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.IntegerField(verbose_name='Contact Number'),
        ),
    ]
